### ISSUE TITLE
Dados do TSE

### ISSUE THREAD

**Issue by rodolfo-viana** [rodolfo-viana/novedejulho#13]
Esta issue é apenas um lembrete para mim mesmo: __mapear o TSE por dados que podem ser raspados__, sobretudo relativos às eleições de 2018 e 2014.

O objetivo é obter informações do pleito dos deputados estaduais. Por exemplo:

- bens declarados,
- empresas contratadas,
- doações

Vou começar a mexer com isso em março.

**Comment by belisards** [comment]
Estou atualizando um script SQL que estrutura os dados de financiamento de campanha, talvez interesse. Aqui é o projeto antigo: http://github.com/belisards/match-tse-odb

que por sua vez foi baseado no https://github.com/rafapolo/tribuna

**Comment by rodolfo-viana** [comment]
@belisards, bom saber! Vou dar uma bisbilhotada amanhã pela manhã. Valeu pela sugestão.

Aliás, falando em SQL, você sabe algum script de Python que infere os tipos de dado num `db` na hora de sua criação? É uma das minhas metas, e estou apenas com isso:

```python
def generate_db():
    hoje = datetime.strftime(datetime.now(), '%Y-%m-%d')
    DATA_DIR = f'data_{hoje}'
    for csvFile in glob.glob(f'{DATA_DIR}/*.csv'):
        file_name = os.path.basename(csvFile)
        with open(csvFile, mode='r', encoding='utf-8') as file_table:
            reader = csv.DictReader(file_table)
            fields = tuple(reader.fieldnames)
            con = sqlite3.connect(f'{DATA_DIR}/novedejulho.db')
            cur = con.cursor()
            cur.execute(f"CREATE TABLE '{file_name}' {fields};")
            reader_2 = csv.reader(file_table)
            for i in reader_2:
                for x in range(len(i)):
                    i[x] = i[x].replace("'", "")  # Para evitar conflito com a aspa de 'INSERT INTO'
                i = tuple(i)
                cur.execute(f"INSERT INTO '{file_name}' VALUES {i};")
            con.commit()
    con.close()
```

Com ele eu crio o `db` e as tables a partir dos arquivos `csv`, mas não faço inferência de tipos...

**Comment by belisards** [comment]
Hmm, não estou certo, mas  a Rows do Turicas não faz isso?

Em sáb, 2 de mar de 2019 00:28, Rodolfo Viana <notifications@github.com>
escreveu:

**Comment by cuducos** [comment]
> você sabe algum script de Python que infere os tipos de dado num `db` na hora de sua criação? 

[Rows](https://github.com/turicas/rows) ; )

**Comment by rodolfo-viana** [comment]
Boa! Vou dar uma estudada em `rows`. Confesso que nunca li sua documentação, nunca brinquei com ele.

**Comment by rodolfo-viana** [comment]
Só para atualizá-los: fiz este script para os dados de candidatura: [`cand.py`](https://github.com/rodolfo-viana/novedejulho/blob/master/novedejulho/cand.py)

**Comment by rodolfo-viana** [comment]
Fiz scripts para baixar candidatos e declarações de bens de 2014 e 2018. Acho que isso é o mais importante.

Dessa forma, fecho esta issue. Fiquem à vontade para reabri-la, se quiserem.
