### ISSUE TITLE
Erro no tqdm

### ISSUE THREAD

**Issue by rodolfo-viana** [rodolfo-viana/novedejulho#17]
@cuducos, eu estou usando `tqdm` para mostrar a barra de progresso de salvamento (não sei usar em outro lugar que não ali). Mas há algum erro: ele mostra uma barra para cada iteração.

Exemplo: 1 barra quando em 0%, outra barra quando em 50%, outra quando em 100%.

Você manja de `tqdm`? Sabe dizer o que posso ter feito errado?

(Aliás, o uso dela está na função `save_file`, em `fetch.py`.)

**Comment by cuducos** [comment]
Então, executei aqui e, na verdade, não tem erro : / Acho que tu espera que o `tqdm` faça o que ele não faz. Me explico:

Ele monta a barra de progresso de acordo com o um iterável, uma sequência. No trecho de código, tu a sequência só tem dois items: `'csv'` e `'xz'`. Então é isso: a barra começa no zero, quando escreve o primeiro arquivo ela pula para 50%, quando escreve o segundo, é o fim, 100%.

O `tqdm` não tem como saber como está o progresso do Pandas salvando um arquivo, pois o Pandas (acho) não tem uma API para isso…

**Comment by rodolfo-viana** [comment]
Acho que não expliquei direito. rs...

`tqdm` cria uma barra para 0%, depois uma segunda barra, separada da primeira, para 50%, e uma terceira, separada das duas anteriores, para 100%.

Aqui:

![image](https://user-images.githubusercontent.com/25807981/54798261-9c8de280-4c36-11e9-91ca-e40e0458a9eb.png)

Deveria ser uma barra só, partindo de 0% até 50%, e depois de 50% a 100%, certo?

**Comment by cuducos** [comment]
Eita! Pode ser alguma coisa do teu terminal. Aqui isso não rola:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/4732915/54816244-89006d00-4c72-11e9-852e-fe4c587d2008.png">

**Comment by rodolfo-viana** [comment]
Deve ser do terminal, mesmo. Mais especificamente do tamanho dele. Quando rodo com terminal quase maximizado, rola de boas:

![image](https://user-images.githubusercontent.com/25807981/54830859-14402980-4c98-11e9-992f-636a48062ac0.png)

Vou fechar essa issue. Valeu, querido. <3
