### ISSUE TITLE
Create a SQLite database with csv files  

### ISSUE THREAD

**Issue by rodolfo-viana** [rodolfo-viana/novedejulho#6]
Look for best ways of creating a SQLite database using csv data. Each file will be a table with its name.

**Comment by cuducos** [comment]
A [Rows](https://github.com/turicas/rows) faz isso automagicamente, já usou? Posso assumir essa _issue_ se ajudar, mas preciso de mais detalhes do caso de uso ; )

**Comment by rodolfo-viana** [comment]
Lol. It was a remainder to myself, but I am glad you read it. :)

I do not want to take your time. But I confess your help would be appreciated.

The ideia is: every dataset one gets from these scripts is inserted into `novedejulho.db` as a table. So the user ends up with a single `.db` file with all the data.

You think it is a good ideia? Or am I being naive?

**Comment by cuducos** [comment]
Sounds pretty useful! I think a possible roadmap would be:

- [ ] Write a module/class/function to handle CSV to SQLite conversion
- [ ] Parametrize it's configurations (e.g. name of the SQLite file)
- [ ] Add this call in every script **or** as an option in the function that writes the _final_ CSV

**Comment by rodolfo-viana** [comment]
@cuducos I got this: [generate_db.py](https://github.com/rodolfo-viana/novedejulho/blob/master/novedejulho/generate_db.py). It worked fine. 

But I changed `fetch.py` some time ago. See here: 

https://github.com/rodolfo-viana/novedejulho/blob/b01578757dd6cac063745f9b9c038e23ccef60f4/novedejulho/ndj_toolbox/fetch.py#L70

That is due to expenses categories already using comma.

Now I must change `csv.reader` and `csv.DictReader` to parse rows considering `delimiter=\t`. I will do that later.

But I must thank you for your kind help offering. <3
